from sqlalchemy import Column, Integer, String, Float, Text, DateTime, ForeignKey, CheckConstraint, func
from app.database import Base

class PracticeSession(Base):
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    status = Column(String(20), nullable=False, server_default="in_progress")
    overall_readiness_score = Column(Float, nullable=True)
    started_at = Column(DateTime, nullable=False, server_default=func.now())
    ended_at = Column(DateTime, nullable=True)

    # Milestone 7: this session's own measured values (single readings,
    # not mean/std - that's what a baseline is for) plus the rule-based
    # feedback generated by comparing them against the baseline that was
    # active at the time. All nullable because a session might be
    # abandoned before it ever gets analyzed.
    eye_contact = Column(Float, nullable=True)
    blink_rate = Column(Float, nullable=True)
    facial_engagement = Column(Float, nullable=True)
    pitch_stability = Column(Float, nullable=True)
    voice_energy = Column(Float, nullable=True)
    speaking_speed = Column(Float, nullable=True)
    pause_duration = Column(Float, nullable=True)
    filler_word_rate = Column(Float, nullable=True)
    # JSON-encoded list of per-feature feedback dicts (see
    # app/ai/readiness.py) - storage/display only, no relational
    # queries needed against individual feedback entries.
    feedback_json = Column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "status IN ('in_progress', 'completed', 'abandoned')",
            name="ck_sessions_status"
        ),
    )