"""add readiness fields to sessions

Revision ID: e0f56ae61b7b
Revises: 63e773fda77d
Create Date: 2026-08-24 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f56ae61b7b'
down_revision: Union[str, Sequence[str], None] = '63e773fda77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Milestone 7: a completed session now stores the raw feature values
    measured during that one live check (same 8 features a baseline
    tracks, but single readings instead of mean/std), plus the
    rule-based feedback generated by comparing them against the user's
    active baseline at the time. `feedback_json` is a JSON-encoded list
    rather than its own table - the shape of one feature's feedback
    (label, value, z-score, severity, message) doesn't need relational
    querying, just storage and display.
    """
    op.add_column('sessions', sa.Column('eye_contact', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('blink_rate', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('facial_engagement', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('pitch_stability', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('voice_energy', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('speaking_speed', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('pause_duration', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('filler_word_rate', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('feedback_json', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('sessions', 'feedback_json')
    op.drop_column('sessions', 'filler_word_rate')
    op.drop_column('sessions', 'pause_duration')
    op.drop_column('sessions', 'speaking_speed')
    op.drop_column('sessions', 'voice_energy')
    op.drop_column('sessions', 'pitch_stability')
    op.drop_column('sessions', 'facial_engagement')
    op.drop_column('sessions', 'blink_rate')
    op.drop_column('sessions', 'eye_contact')
