"""create users, sessions, baseline_profiles tables

Revision ID: fd062001f86a
Revises: 
Create Date: 2026-08-05 11:46:05.336579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd062001f86a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('baseline_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eye_contact_mean', sa.Float(), nullable=True),
    sa.Column('eye_contact_std', sa.Float(), nullable=True),
    sa.Column('blink_rate_mean', sa.Float(), nullable=True),
    sa.Column('blink_rate_std', sa.Float(), nullable=True),
    sa.Column('speaking_speed_mean', sa.Float(), nullable=True),
    sa.Column('speaking_speed_std', sa.Float(), nullable=True),
    sa.Column('pitch_stability_mean', sa.Float(), nullable=True),
    sa.Column('pitch_stability_std', sa.Float(), nullable=True),
    sa.Column('voice_energy_mean', sa.Float(), nullable=True),
    sa.Column('voice_energy_std', sa.Float(), nullable=True),
    sa.Column('pause_duration_mean', sa.Float(), nullable=True),
    sa.Column('pause_duration_std', sa.Float(), nullable=True),
    sa.Column('filler_word_rate_mean', sa.Float(), nullable=True),
    sa.Column('filler_word_rate_std', sa.Float(), nullable=True),
    sa.Column('facial_engagement_mean', sa.Float(), nullable=True),
    sa.Column('facial_engagement_std', sa.Float(), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('calibrated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseline_profiles_id'), 'baseline_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_baseline_profiles_user_id'), 'baseline_profiles', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False),
    sa.Column('overall_readiness_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_baseline_profiles_user_id'), table_name='baseline_profiles')
    op.drop_index(op.f('ix_baseline_profiles_id'), table_name='baseline_profiles')
    op.drop_table('baseline_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
